#line 2 "demo-c.c"

#line 4 "demo-c.c"

#define  YY_INT_ALIGNED short int

/*SKEL*/ /* A lexical scanner generated by flex */
/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/
/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

/*SKEL*/
/*SKEL*/ #define FLEX_SCANNER
/*SKEL*/ #define YY_FLEX_MAJOR_VERSION 2
/*SKEL*/ #define YY_FLEX_MINOR_VERSION 6
/*SKEL*/ #define YY_FLEX_SUBMINOR_VERSION 0
/*SKEL*/ #if YY_FLEX_SUBMINOR_VERSION > 0
/*SKEL*/ #define FLEX_BETA
/*SKEL*/ #endif
/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-c++-only */
/* %endif */
/*SKEL*/
/* %if-c-only */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %endif */
/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-c-only */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %endif */
/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/ /* First, we deal with  platform-specific or compiler-specific issues. */
/*SKEL*/
/*SKEL*/ /* begin standard C headers. */
/* %if-c-only */
/*SKEL*/ #include <stdio.h>
/*SKEL*/ #include <string.h>
/*SKEL*/ #include <errno.h>
/*SKEL*/ #include <stdlib.h>
/* %endif */
/*SKEL*/
/* %if-tables-serialization */
/* %endif */
/*SKEL*/ /* end standard C headers. */
/*SKEL*/
/* %if-c-or-c++ */
/*SKEL*/ /* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */
/*SKEL*/
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ #ifdef __cplusplus
/*SKEL*/
/*SKEL*/ /* The "const" storage-class-modifier is valid. */
/*SKEL*/ #define YY_USE_CONST
/*SKEL*/
/*SKEL*/ #else	/* ! __cplusplus */
/*SKEL*/
/*SKEL*/ /* C99 requires __STDC__ to be defined as 1. */
/*SKEL*/ #if defined (__STDC__)
/*SKEL*/
/*SKEL*/ #define YY_USE_CONST
/*SKEL*/
/*SKEL*/ #endif	/* defined (__STDC__) */
/*SKEL*/ #endif	/* ! __cplusplus */
/*SKEL*/
/*SKEL*/ #ifdef YY_USE_CONST
/*SKEL*/ #define yyconst const
/*SKEL*/ #else
/*SKEL*/ #define yyconst
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %not-for-header */

/*SKEL*/ /* Returned upon end-of-file. */
/*SKEL*/ #define YY_NULL 0
/* %ok-for-header */

/*SKEL*/
/* %not-for-header */

/*SKEL*/ /* Promotes a possibly negative, possibly signed char to an unsigned */
/*SKEL*/ /* integer for use as an array index.  If the signed char is negative, */
/*SKEL*/ /* we want to instead treat it as an 8-bit unsigned char, hence the */
/*SKEL*/ /* double cast. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-reentrant */
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-not-reentrant */
/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/

/*SKEL*/
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Enter a start condition.  This macro really ought to take a parameter, */
/*SKEL*/ /* but we do it the disgusting crufty way forced on us by the ()-less */
/*SKEL*/ /* definition of BEGIN. */
/*SKEL*/ /* */
/*SKEL*/ #define BEGIN (yy_start) = 1 + 2 *
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Translate the current start state into a value that can be later handed */
/*SKEL*/ /* to BEGIN to return to the state.  The YYSTATE alias is for lex */
/*SKEL*/ /* compatibility. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_START (((yy_start) - 1) / 2)
/*SKEL*/ #define YYSTATE YY_START
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Action number for EOF rule of a given start state. */
/*SKEL*/ #define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Special action meaning "start processing a new file". */
/*SKEL*/ #define YY_NEW_FILE yyrestart(yyin  )
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define YY_END_OF_BUFFER_CHAR 0
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Size of default input buffer. */
/*SKEL*/ #ifndef YY_BUF_SIZE
/*SKEL*/ #ifdef __ia64__
/*SKEL*/ /* On IA-64, the buffer size is 16k, not 8k. */
/*SKEL*/ /* Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case. */
/*SKEL*/ /* Ditto for the __ia64__ case accordingly. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_BUF_SIZE 32768
/*SKEL*/ #else
/*SKEL*/ #define YY_BUF_SIZE 16384
/*SKEL*/ #endif /* __ia64__ */
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* The state buf must be large enough to hold one state per character in the main buffer. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifndef YY_TYPEDEF_YY_BUFFER_STATE
/*SKEL*/ #define YY_TYPEDEF_YY_BUFFER_STATE
/*SKEL*/ typedef struct yy_buffer_state *YY_BUFFER_STATE;
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/ #ifndef YY_TYPEDEF_YY_SIZE_T
/*SKEL*/ #define YY_TYPEDEF_YY_SIZE_T
/*SKEL*/ typedef size_t yy_size_t;
/*SKEL*/ #endif
/*SKEL*/
/* %if-not-reentrant */
/*SKEL*/ extern yy_size_t yyleng;
/* %endif */
/*SKEL*/
/* %if-c-only */
/* %if-not-reentrant */
/*SKEL*/ extern FILE *yyin, *yyout;
/* %endif */
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define EOB_ACT_CONTINUE_SCAN 0
/*SKEL*/ #define EOB_ACT_END_OF_FILE 1
/*SKEL*/ #define EOB_ACT_LAST_MATCH 2
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/     #define YY_LESS_LINENO(n)
/*SKEL*/     #define YY_LINENO_REWIND_TO(ptr)
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Return all but the first "n" matched characters back to the input stream. */
/*SKEL*/ #define yyless(n) \
/*SKEL*/ 	do \
/*SKEL*/ 		{ \
/*SKEL*/ 		/* Undo effects of setting up yytext. */ \
/*SKEL*/         int yyless_macro_arg = (n); \
/*SKEL*/         YY_LESS_LINENO(yyless_macro_arg);\
/*SKEL*/ 		*yy_cp = (yy_hold_char); \
/*SKEL*/ 		YY_RESTORE_YY_MORE_OFFSET \
/*SKEL*/ 		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
/*SKEL*/ 		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
/*SKEL*/ 		} \
/*SKEL*/ 	while ( 0 )
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define unput(c) yyunput( c, (yytext_ptr)  )
/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifndef YY_STRUCT_YY_BUFFER_STATE
/*SKEL*/ #define YY_STRUCT_YY_BUFFER_STATE
/*SKEL*/ struct yy_buffer_state
/*SKEL*/ 	{
/* %if-c-only */
/*SKEL*/ 	FILE *yy_input_file;
/* %endif */
/*SKEL*/
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ 	char *yy_ch_buf;		/* input buffer */
/*SKEL*/ 	char *yy_buf_pos;		/* current position in input buffer */
/*SKEL*/
/*SKEL*/ 	/* Size of input buffer in bytes, not including room for EOB */
/*SKEL*/ 	/* characters. */
/*SKEL*/ 	/* */
/*SKEL*/ 	yy_size_t yy_buf_size;
/*SKEL*/
/*SKEL*/ 	/* Number of characters read into yy_ch_buf, not including EOB */
/*SKEL*/ 	/* characters. */
/*SKEL*/ 	/* */
/*SKEL*/ 	yy_size_t yy_n_chars;
/*SKEL*/
/*SKEL*/ 	/* Whether we "own" the buffer - i.e., we know we created it, */
/*SKEL*/ 	/* and can realloc() it to grow it, and should free() it to */
/*SKEL*/ 	/* delete it. */
/*SKEL*/ 	/* */
/*SKEL*/ 	int yy_is_our_buffer;
/*SKEL*/
/*SKEL*/ 	/* Whether this is an "interactive" input source; if so, and */
/*SKEL*/ 	/* if we're using stdio for input, then we want to use getc() */
/*SKEL*/ 	/* instead of fread(), to make sure we stop fetching input after */
/*SKEL*/ 	/* each newline. */
/*SKEL*/ 	/* */
/*SKEL*/ 	int yy_is_interactive;
/*SKEL*/
/*SKEL*/ 	/* Whether we're considered to be at the beginning of a line. */
/*SKEL*/ 	/* If so, '^' rules will be active on the next match, otherwise */
/*SKEL*/ 	/* not. */
/*SKEL*/ 	/* */
/*SKEL*/ 	int yy_at_bol;
/*SKEL*/
/*SKEL*/     int yy_bs_lineno; /**< The line count. */
/*SKEL*/     int yy_bs_column; /**< The column count. */
/*SKEL*/
/*SKEL*/
/*SKEL*/ 	/* Whether to try to fill the input buffer when we reach the */
/*SKEL*/ 	/* end of it. */
/*SKEL*/ 	/* */
/*SKEL*/ 	int yy_fill_buffer;
/*SKEL*/
/*SKEL*/ 	int yy_buffer_status;
/*SKEL*/
/*SKEL*/ #define YY_BUFFER_NEW 0
/*SKEL*/ #define YY_BUFFER_NORMAL 1
/*SKEL*/ 	/* When an EOF's been seen but there's still some text to process */
/*SKEL*/ 	/* then we mark the buffer as YY_EOF_PENDING, to indicate that we */
/*SKEL*/ 	/* shouldn't try reading from the input source any more.  We might */
/*SKEL*/ 	/* still have a bunch of tokens to match, though, because of */
/*SKEL*/ 	/* possible backing-up. */
/*SKEL*/ 	/* */
/*SKEL*/ 	/* When we actually see the EOF, we change the status to "new" */
/*SKEL*/ 	/* (via yyrestart()), so that the user can continue scanning by */
/*SKEL*/ 	/* just pointing yyin at a new input file. */
/*SKEL*/ 	/* */
/*SKEL*/ #define YY_BUFFER_EOF_PENDING 2
/*SKEL*/
/*SKEL*/ 	};
/*SKEL*/ #endif /* !YY_STRUCT_YY_BUFFER_STATE */
/*SKEL*/
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/*SKEL*/
/*SKEL*/ /* Stack of input buffers. */
/*SKEL*/ static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
/*SKEL*/ static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
/*SKEL*/ static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* We provide macros for accessing buffer states in case in the */
/*SKEL*/ /* future we want to put the buffer states in a more general */
/*SKEL*/ /* "scanner state". */
/*SKEL*/ /* */
/*SKEL*/ /* Returns the top of the stack, or NULL. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
/*SKEL*/                           ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
/*SKEL*/                           : NULL)
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Same as previous macro, but useful when we know that the buffer stack is not */
/*SKEL*/ /* NULL or when we need an lvalue. For internal use only. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
/*SKEL*/
/*SKEL*/
/* %if-c-only Standard (non-C++) definition */
/*SKEL*/
/* %if-not-reentrant */
/* %not-for-header */

/*SKEL*/ /* yy_hold_char holds the character lost when yytext is formed. */
/*SKEL*/ static char yy_hold_char;
/*SKEL*/ static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
/*SKEL*/ yy_size_t yyleng;
/*SKEL*/
/*SKEL*/ /* Points to current character in buffer. */
/*SKEL*/ static char *yy_c_buf_p = (char *) 0;
/*SKEL*/ static int yy_init = 0;		/* whether we need to initialize */
/*SKEL*/ static int yy_start = 0;	/* start state number */
/*SKEL*/
/*SKEL*/ /* Flag which is used to allow yywrap()'s to do buffer switches */
/*SKEL*/ /* instead of setting up a fresh yyin.  A bit of a hack ... */
/*SKEL*/ /* */
/*SKEL*/ static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */
/*SKEL*/
/*SKEL*/ void yyrestart (FILE *input_file  );
/*SKEL*/ void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
/*SKEL*/ YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
/*SKEL*/ void yy_delete_buffer (YY_BUFFER_STATE b  );
/*SKEL*/ void yy_flush_buffer (YY_BUFFER_STATE b  );
/*SKEL*/ void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
/*SKEL*/ void yypop_buffer_state (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/ static void yyensure_buffer_stack (void );
/*SKEL*/ static void yy_load_buffer_state (void );
/*SKEL*/ static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )
/*SKEL*/
/*SKEL*/
/*SKEL*/ YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
/*SKEL*/ YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
/*SKEL*/ YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );
/*SKEL*/
/* %endif */
/*SKEL*/
/*SKEL*/ void *yyalloc (yy_size_t  );
/*SKEL*/ void *yyrealloc (void *,yy_size_t  );
/*SKEL*/ void yyfree (void *  );
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define yy_new_buffer yy_create_buffer
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define yy_set_interactive(is_interactive) \
/*SKEL*/ 	{ \
/*SKEL*/ 	if ( ! YY_CURRENT_BUFFER ){ \
/*SKEL*/         yyensure_buffer_stack (); \
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE =    \
/*SKEL*/             yy_create_buffer(yyin,YY_BUF_SIZE ); \
/*SKEL*/ 	} \
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
/*SKEL*/ 	}
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define yy_set_bol(at_bol) \
/*SKEL*/ 	{ \
/*SKEL*/ 	if ( ! YY_CURRENT_BUFFER ){\
/*SKEL*/         yyensure_buffer_stack (); \
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE =    \
/*SKEL*/             yy_create_buffer(yyin,YY_BUF_SIZE ); \
/*SKEL*/ 	} \
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
/*SKEL*/ 	}
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
/*SKEL*/
/*SKEL*/
/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext
/*SKEL*/
/*SKEL*/
/* %% [1.5] DFA */
/*SKEL*/
/*SKEL*/
/* %if-c-only Standard (non-C++) definition */
/*SKEL*/
/*SKEL*/
/*SKEL*/ static yy_state_type yy_get_previous_state (void );
/*SKEL*/ static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
/*SKEL*/ static int yy_get_next_buffer (void );
/*SKEL*/ #if defined(__GNUC__) && __GNUC__ >= 3
/*SKEL*/ __attribute__((__noreturn__))
/*SKEL*/ #endif
/*SKEL*/ static void yy_fatal_error (yyconst char msg[]  );
/*SKEL*/
/*SKEL*/
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Done after the current pattern has been matched and before the */
/*SKEL*/ /* corresponding action - sets up yytext. */
/*SKEL*/ /* */
/*SKEL*/ #define YY_DO_BEFORE_ACTION \
/*SKEL*/ 	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
/*SKEL*/ 	(yy_hold_char) = *yy_cp; \
/*SKEL*/ 	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
/*SKEL*/ 	(yy_c_buf_p) = yy_cp;
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 2
#define YY_END_OF_BUFFER 3
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[7] =
    {   0,
        0,    0,    3,    2,    1,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[3] =
    {   0,
        1,    1
    } ;

static yyconst flex_uint16_t yy_base[7] =
    {   0,
        0,    0,    3,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_def[7] =
    {   0,
        6,    1,    6,    6,    6,    0
    } ;

static yyconst flex_uint16_t yy_nxt[7] =
    {   0,
        4,    5,    6,    3,    6,    6
    } ;

static yyconst flex_int16_t yy_chk[7] =
    {   0,
        1,    1,    3,    6,    6,    6
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[2] =
    {   0,
       15
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "demo.l"
#line 2 "demo.l"

#include <stdio.h>

int yywrap()
{
    return 1;
}

#line 705 "demo-c.c"
/*SKEL*/
/*SKEL*/

/*SKEL*/ #define INITIAL 0

/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifndef YY_NO_UNISTD_H
/*SKEL*/ /* Special case for "unistd.h", since it is non-ANSI. We include it way */
/*SKEL*/ /* down here because we want the user's section 1 to have been scanned first. */
/*SKEL*/ /* The user has a chance to override it with an option. */
/*SKEL*/ /* */
/* %if-c-only */
/*SKEL*/ #include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifndef YY_EXTRA_TYPE
/*SKEL*/ #define YY_EXTRA_TYPE void *
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/*SKEL*/
/*SKEL*/ static int yy_init_globals (void );
/*SKEL*/
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/*SKEL*/
/*SKEL*/ /* Accessor methods to globals. */
/*SKEL*/ /*  These are made visible to non-reentrant scanners for convenience. */
/*SKEL*/
/*SKEL*/
/*SKEL*/ int yylex_destroy (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ int yyget_debug (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_debug (int debug_flag  );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ YY_EXTRA_TYPE yyget_extra (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_extra (YY_EXTRA_TYPE user_defined  );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ FILE *yyget_in (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_in  (FILE * _in_str  );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ FILE *yyget_out (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_out  (FILE * _out_str  );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ yy_size_t yyget_leng (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ char *yyget_text (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ int yyget_lineno (void );
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_lineno (int _line_number  );
/*SKEL*/
/*SKEL*/

/*SKEL*/

/*SKEL*/
/* %if-bison-bridge */
/* %endif */
/*SKEL*/
/*SKEL*/ /* Macros after this point can all be overridden by user definitions in */
/*SKEL*/ /* section 1. */
/*SKEL*/ /* */
/*SKEL*/
/*SKEL*/ #ifndef YY_SKIP_YYWRAP
/*SKEL*/ #ifdef __cplusplus
/*SKEL*/ extern "C" int yywrap (void );
/*SKEL*/ #else
/*SKEL*/ extern int yywrap (void );
/*SKEL*/ #endif
/*SKEL*/ #endif
/*SKEL*/
/* %not-for-header */

/*SKEL*/ #ifndef YY_NO_UNPUT
/*SKEL*/
/*SKEL*/     static void yyunput (int c,char *buf_ptr  );
/*SKEL*/
/*SKEL*/ #endif
/* %ok-for-header */

/* %endif */
/*SKEL*/
/*SKEL*/ #ifndef yytext_ptr
/*SKEL*/ static void yy_flex_strncpy (char *,yyconst char *,int );
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/ #ifdef YY_NEED_STRLEN
/*SKEL*/ static int yy_flex_strlen (yyconst char * );
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/ #ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/*SKEL*/ #ifdef __cplusplus
/*SKEL*/ static int yyinput (void );
/*SKEL*/ #else
/*SKEL*/ static int input (void );
/*SKEL*/ #endif
/* %ok-for-header */

/* %endif */
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/* %if-c-only */
/*SKEL*/

/*SKEL*/
/* %endif */
/*SKEL*/
/*SKEL*/ /* Amount of stuff to slurp up with each read. */
/*SKEL*/ #ifndef YY_READ_BUF_SIZE
/*SKEL*/ #ifdef __ia64__
/*SKEL*/ /* On IA-64, the buffer size is 16k, not 8k */
/*SKEL*/ #define YY_READ_BUF_SIZE 16384
/*SKEL*/ #else
/*SKEL*/ #define YY_READ_BUF_SIZE 8192
/*SKEL*/ #endif /* __ia64__ */
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Copy whatever the last rule matched to the standard output. */
/*SKEL*/ #ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/*SKEL*/ /* This used to be an fputs(), but since the string might contain NUL's, */
/*SKEL*/ /* we now use fwrite(). */
/*SKEL*/ /* */
/*SKEL*/ #define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL, */
/*SKEL*/ /* is returned in "result". */
/*SKEL*/ /* */
/*SKEL*/ #ifndef YY_INPUT
/*SKEL*/ #define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
/*SKEL*/ \
/* %if-c++-only C++ definition \ */\
/* %endif */
/*SKEL*/
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* No semi-colon after return; correct usage is to write "yyterminate();" - */
/*SKEL*/ /* we don't want an extra ';' after the "return" because that will cause */
/*SKEL*/ /* some compilers to complain about unreachable statements. */
/*SKEL*/ /* */
/*SKEL*/ #ifndef yyterminate
/*SKEL*/ #define yyterminate() return YY_NULL
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Number of entries by which start-condition stack grows. */
/*SKEL*/ #ifndef YY_START_STACK_INCR
/*SKEL*/ #define YY_START_STACK_INCR 25
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Report a fatal error. */
/*SKEL*/ #ifndef YY_FATAL_ERROR
/* %if-c-only */
/*SKEL*/ #define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/*SKEL*/ /* end tables serialization structures and prototypes */
/*SKEL*/
/* %ok-for-header */

/*SKEL*/
/*SKEL*/ /* Default declaration of generated scanner - a define so the user can */
/*SKEL*/ /* easily add parameters. */
/*SKEL*/ /* */
/*SKEL*/ #ifndef YY_DECL
/*SKEL*/ #define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/*SKEL*/
/*SKEL*/

/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/ extern int yylex (void);
/*SKEL*/
/*SKEL*/ #define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
/*SKEL*/ #endif /* !YY_DECL */
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Code executed at the beginning of each rule, after yytext and yyleng */
/*SKEL*/ /* have been set up. */
/*SKEL*/ /* */
/*SKEL*/ #ifndef YY_USER_ACTION
/*SKEL*/ #define YY_USER_ACTION
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Code executed at the end of each rule. */
/*SKEL*/ #ifndef YY_BREAK
/*SKEL*/ #define YY_BREAK /*LINTED*/break;
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION
/*SKEL*/
/*SKEL*/
/* %not-for-header */

/*SKEL*/ /* The main scanner function which does all the work. */
/*SKEL*/
/*SKEL*/ YY_DECL
/*SKEL*/ {
/*SKEL*/ 	yy_state_type yy_current_state;
/*SKEL*/ 	char *yy_cp, *yy_bp;
/*SKEL*/ 	int yy_act;
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/ 	if ( !(yy_init) )
/*SKEL*/ 		{
/*SKEL*/ 		(yy_init) = 1;
/*SKEL*/
/*SKEL*/ #ifdef YY_USER_INIT
/*SKEL*/ 		YY_USER_INIT;
/*SKEL*/ #endif
/*SKEL*/

/*SKEL*/
/*SKEL*/ 		if ( ! (yy_start) )
/*SKEL*/ 			(yy_start) = 1;	/* first start state */
/*SKEL*/
/*SKEL*/ 		if ( ! yyin )
/* %if-c-only */
/*SKEL*/ 			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ 		if ( ! yyout )
/* %if-c-only */
/*SKEL*/ 			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ 		if ( ! YY_CURRENT_BUFFER ) {
/*SKEL*/ 			yyensure_buffer_stack ();
/*SKEL*/ 			YY_CURRENT_BUFFER_LVALUE =
/*SKEL*/ 				yy_create_buffer(yyin,YY_BUF_SIZE );
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 		yy_load_buffer_state( );
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	{
/* %% [7.0] user's declarations go here */
#line 13 "demo.l"


#line 1067 "demo-c.c"
/*SKEL*/
/*SKEL*/ 	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
/*SKEL*/ 		{
/* %% [8.0] yymore()-related code goes here */
/*SKEL*/ 		yy_cp = (yy_c_buf_p);
/*SKEL*/
/*SKEL*/ 		/* Support of yytext. */
/*SKEL*/ 		*yy_cp = (yy_hold_char);
/*SKEL*/
/*SKEL*/ 		/* yy_bp points to the position in yy_ch_buf of the start of */
/*SKEL*/ 		/* the current run. */
/*SKEL*/ 		/* */
/*SKEL*/ 		yy_bp = yy_cp;
/*SKEL*/
/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 7 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 4 );
/*SKEL*/
/*SKEL*/ yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}
/*SKEL*/
/*SKEL*/ 		YY_DO_BEFORE_ACTION;
/*SKEL*/
/* %% [11.0] code for yylineno update goes here */

/*SKEL*/
/*SKEL*/ do_action:	/* This label is used only to access EOF actions. */
/*SKEL*/
/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 2 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 2 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 3 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}
/*SKEL*/
/*SKEL*/ 		switch ( yy_act )
/*SKEL*/ 	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "demo.l"
printf("Go");
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "demo.l"
ECHO;
	YY_BREAK
#line 1158 "demo-c.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();
/*SKEL*/
/*SKEL*/ 	case YY_END_OF_BUFFER:
/*SKEL*/ 		{
/*SKEL*/ 		/* Amount of text matched not including the EOB char. */
/*SKEL*/ 		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;
/*SKEL*/
/*SKEL*/ 		/* Undo the effects of YY_DO_BEFORE_ACTION. */
/*SKEL*/ 		*yy_cp = (yy_hold_char);
/*SKEL*/ 		YY_RESTORE_YY_MORE_OFFSET
/*SKEL*/
/*SKEL*/ 		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
/*SKEL*/ 			{
/*SKEL*/ 			/* We're scanning a new file or input source.  It's */
/*SKEL*/ 			/* possible that this happened because the user */
/*SKEL*/ 			/* just pointed yyin at a new source and called */
/*SKEL*/ 			/* yylex().  If so, then we have to assure */
/*SKEL*/ 			/* consistency between YY_CURRENT_BUFFER and our */
/*SKEL*/ 			/* globals.  Here is the right place to do so, because */
/*SKEL*/ 			/* this is the first action (other than possibly a */
/*SKEL*/ 			/* back-up) that will match for the new input source. */
/*SKEL*/ 			/* */
/*SKEL*/ 			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/*SKEL*/ 			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ 			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
/*SKEL*/ 			}
/*SKEL*/
/*SKEL*/ 		/* Note that here we test for yy_c_buf_p "<=" to the position */
/*SKEL*/ 		/* of the first EOB in the buffer, since yy_c_buf_p will */
/*SKEL*/ 		/* already have been incremented past the NUL character */
/*SKEL*/ 		/* (since all states make transitions on EOB to the */
/*SKEL*/ 		/* end-of-buffer state).  Contrast this with the test */
/*SKEL*/ 		/* in input(). */
/*SKEL*/ 		/* */
/*SKEL*/ 		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
/*SKEL*/ 			{ /* This was really a NUL. */
/*SKEL*/ 			yy_state_type yy_next_state;
/*SKEL*/
/*SKEL*/ 			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;
/*SKEL*/
/*SKEL*/ 			yy_current_state = yy_get_previous_state(  );
/*SKEL*/
/*SKEL*/ 			/* Okay, we're now positioned to make the NUL */
/*SKEL*/ 			/* transition.  We couldn't have */
/*SKEL*/ 			/* yy_get_previous_state() go ahead and do it */
/*SKEL*/ 			/* for us because it doesn't know how to deal */
/*SKEL*/ 			/* with the possibility of jamming (and we don't */
/*SKEL*/ 			/* want to build jamming into it because then it */
/*SKEL*/ 			/* will run more slowly). */
/*SKEL*/ 			/* */
/*SKEL*/
/*SKEL*/ 			yy_next_state = yy_try_NUL_trans( yy_current_state );
/*SKEL*/
/*SKEL*/ 			yy_bp = (yytext_ptr) + YY_MORE_ADJ;
/*SKEL*/
/*SKEL*/ 			if ( yy_next_state )
/*SKEL*/ 				{
/*SKEL*/ 				/* Consume the NUL. */
/*SKEL*/ 				yy_cp = ++(yy_c_buf_p);
/*SKEL*/ 				yy_current_state = yy_next_state;
/*SKEL*/ 				goto yy_match;
/*SKEL*/ 				}
/*SKEL*/
/*SKEL*/ 			else
/*SKEL*/ 				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
/*SKEL*/ 				goto yy_find_action;
/*SKEL*/ 				}
/*SKEL*/ 			}
/*SKEL*/
/*SKEL*/ 		else switch ( yy_get_next_buffer(  ) )
/*SKEL*/ 			{
/*SKEL*/ 			case EOB_ACT_END_OF_FILE:
/*SKEL*/ 				{
/*SKEL*/ 				(yy_did_buffer_switch_on_eof) = 0;
/*SKEL*/
/*SKEL*/ 				if ( yywrap( ) )
/*SKEL*/ 					{
/*SKEL*/ 					/* Note: because we've taken care in */
/*SKEL*/ 					/* yy_get_next_buffer() to have set up */
/*SKEL*/ 					/* yytext, we can now set up */
/*SKEL*/ 					/* yy_c_buf_p so that if some total */
/*SKEL*/ 					/* hoser (like flex itself) wants to */
/*SKEL*/ 					/* call the scanner after we return the */
/*SKEL*/ 					/* YY_NULL, it'll still work - another */
/*SKEL*/ 					/* YY_NULL will get returned. */
/*SKEL*/ 					/* */
/*SKEL*/ 					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;
/*SKEL*/
/*SKEL*/ 					yy_act = YY_STATE_EOF(YY_START);
/*SKEL*/ 					goto do_action;
/*SKEL*/ 					}
/*SKEL*/
/*SKEL*/ 				else
/*SKEL*/ 					{
/*SKEL*/ 					if ( ! (yy_did_buffer_switch_on_eof) )
/*SKEL*/ 						YY_NEW_FILE;
/*SKEL*/ 					}
/*SKEL*/ 				break;
/*SKEL*/ 				}
/*SKEL*/
/*SKEL*/ 			case EOB_ACT_CONTINUE_SCAN:
/*SKEL*/ 				(yy_c_buf_p) =
/*SKEL*/ 					(yytext_ptr) + yy_amount_of_matched_text;
/*SKEL*/
/*SKEL*/ 				yy_current_state = yy_get_previous_state(  );
/*SKEL*/
/*SKEL*/ 				yy_cp = (yy_c_buf_p);
/*SKEL*/ 				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
/*SKEL*/ 				goto yy_match;
/*SKEL*/
/*SKEL*/ 			case EOB_ACT_LAST_MATCH:
/*SKEL*/ 				(yy_c_buf_p) =
/*SKEL*/ 				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];
/*SKEL*/
/*SKEL*/ 				yy_current_state = yy_get_previous_state(  );
/*SKEL*/
/*SKEL*/ 				yy_cp = (yy_c_buf_p);
/*SKEL*/ 				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
/*SKEL*/ 				goto yy_find_action;
/*SKEL*/ 			}
/*SKEL*/ 		break;
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	default:
/*SKEL*/ 		YY_FATAL_ERROR(
/*SKEL*/ 			"fatal flex scanner internal error--no action found" );
/*SKEL*/ 	} /* end of action switch */
/*SKEL*/ 		} /* end of scanning one token */
/*SKEL*/ 	} /* end of user's declarations */
/*SKEL*/ } /* end of yylex */
/* %ok-for-header */

/*SKEL*/
/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* yy_get_next_buffer - try to read in a new buffer */
/*SKEL*/  /* */
/*SKEL*/  /* Returns a code representing an action: */
/*SKEL*/  /*	EOB_ACT_LAST_MATCH - */
/*SKEL*/  /*	EOB_ACT_CONTINUE_SCAN - continue scanning from current position */
/*SKEL*/  /*	EOB_ACT_END_OF_FILE - end of file */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/ static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/      	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
/*SKEL*/ 	char *source = (yytext_ptr);
/*SKEL*/ 	yy_size_t number_to_move, i;
/*SKEL*/ 	int ret_val;
/*SKEL*/
/*SKEL*/ 	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
/*SKEL*/ 		YY_FATAL_ERROR(
/*SKEL*/ 		"fatal flex scanner internal error--end of buffer missed" );
/*SKEL*/
/*SKEL*/ 	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
/*SKEL*/ 		{ /* Don't try to fill the buffer, so this is an EOF. */
/*SKEL*/ 		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
/*SKEL*/ 			{
/*SKEL*/ 			/* We matched a single character, the EOB, so */
/*SKEL*/ 			 /* treat this as a final EOF. */
/*SKEL*/ 			 /**/
/*SKEL*/ 			return EOB_ACT_END_OF_FILE;
/*SKEL*/ 			}
/*SKEL*/
/*SKEL*/ 		else
/*SKEL*/ 			{
/*SKEL*/ 			/* We matched some text prior to the EOB, first */
/*SKEL*/ 			 /* process it. */
/*SKEL*/ 			 /**/
/*SKEL*/ 			return EOB_ACT_LAST_MATCH;
/*SKEL*/ 			}
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	/* Try to read more data. */
/*SKEL*/
/*SKEL*/ 	/* First move last chars to start of buffer. */
/*SKEL*/ 	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;
/*SKEL*/
/*SKEL*/ 	for ( i = 0; i < number_to_move; ++i )
/*SKEL*/ 		*(dest++) = *(source++);
/*SKEL*/
/*SKEL*/ 	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
/*SKEL*/ 		/* don't do the read, it's not guaranteed to return an EOF, */
/*SKEL*/ 		 /* just force an EOF */
/*SKEL*/ 		 /**/
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
/*SKEL*/
/*SKEL*/ 	else
/*SKEL*/ 		{
/*SKEL*/ 			yy_size_t num_to_read =
/*SKEL*/ 			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
/*SKEL*/
/*SKEL*/ 		while ( num_to_read <= 0 )
/*SKEL*/ 			{ /* Not enough room in the buffer - grow it. */
/*SKEL*/
/*SKEL*/ 			/* just a shorter name for the current buffer */
/*SKEL*/ 			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;
/*SKEL*/
/*SKEL*/ 			int yy_c_buf_p_offset =
/*SKEL*/ 				(int) ((yy_c_buf_p) - b->yy_ch_buf);
/*SKEL*/
/*SKEL*/ 			if ( b->yy_is_our_buffer )
/*SKEL*/ 				{
/*SKEL*/ 				yy_size_t new_size = b->yy_buf_size * 2;
/*SKEL*/
/*SKEL*/ 				if ( new_size <= 0 )
/*SKEL*/ 					b->yy_buf_size += b->yy_buf_size / 8;
/*SKEL*/ 				else
/*SKEL*/ 					b->yy_buf_size *= 2;
/*SKEL*/
/*SKEL*/ 				b->yy_ch_buf = (char *)
/*SKEL*/ 					/* Include room in for 2 EOB chars. */
/*SKEL*/ 					yyrealloc((void *) b->yy_ch_buf,/*SKEL*/ 							 b->yy_buf_size + 2  );
/*SKEL*/ 				}
/*SKEL*/ 			else
/*SKEL*/ 				/* Can't grow it, we don't own it. */
/*SKEL*/ 				b->yy_ch_buf = 0;
/*SKEL*/
/*SKEL*/ 			if ( ! b->yy_ch_buf )
/*SKEL*/ 				YY_FATAL_ERROR(
/*SKEL*/ 				"fatal error - scanner input buffer overflow" );
/*SKEL*/
/*SKEL*/ 			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];
/*SKEL*/
/*SKEL*/ 			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
/*SKEL*/ 						number_to_move - 1;
/*SKEL*/
/*SKEL*/ 			}
/*SKEL*/
/*SKEL*/ 		if ( num_to_read > YY_READ_BUF_SIZE )
/*SKEL*/ 			num_to_read = YY_READ_BUF_SIZE;
/*SKEL*/
/*SKEL*/ 		/* Read in more data. */
/*SKEL*/ 		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
/*SKEL*/ 			(yy_n_chars), num_to_read );
/*SKEL*/
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	if ( (yy_n_chars) == 0 )
/*SKEL*/ 		{
/*SKEL*/ 		if ( number_to_move == YY_MORE_ADJ )
/*SKEL*/ 			{
/*SKEL*/ 			ret_val = EOB_ACT_END_OF_FILE;
/*SKEL*/ 			yyrestart(yyin  );
/*SKEL*/ 			}
/*SKEL*/
/*SKEL*/ 		else
/*SKEL*/ 			{
/*SKEL*/ 			ret_val = EOB_ACT_LAST_MATCH;
/*SKEL*/ 			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
/*SKEL*/ 				YY_BUFFER_EOF_PENDING;
/*SKEL*/ 			}
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	else
/*SKEL*/ 		ret_val = EOB_ACT_CONTINUE_SCAN;
/*SKEL*/
/*SKEL*/ 	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
/*SKEL*/ 		/* Extend the array by 50%, plus the number we really need. */
/*SKEL*/ 		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(/*SKEL*/ 			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
/*SKEL*/ 		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
/*SKEL*/ 			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
/*SKEL*/ 	}
/*SKEL*/
/*SKEL*/ 	(yy_n_chars) += number_to_move;
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;
/*SKEL*/
/*SKEL*/ 	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];
/*SKEL*/
/*SKEL*/ 	return ret_val;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* yy_get_previous_state - get the state just before the EOB char was reached */
/*SKEL*/
/* %if-c-only */
/* %not-for-header */

/*SKEL*/     static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/ 	yy_state_type yy_current_state;
/*SKEL*/ 	char *yy_cp;
/*SKEL*/
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
/*SKEL*/
/*SKEL*/ 	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
/*SKEL*/ 		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 7 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	return yy_current_state;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* yy_try_NUL_trans - try to make a transition on the NUL character */
/*SKEL*/  /* */
/*SKEL*/  /* synopsis */
/*SKEL*/  /*	next_state = yy_try_NUL_trans( current_state ); */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/ 	int yy_is_jam;
/*SKEL*/     /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 7 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 6);
/*SKEL*/
/*SKEL*/ 	 	return yy_is_jam ? 0 : yy_current_state;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifndef YY_NO_UNPUT
/* %if-c-only */
/*SKEL*/
/*SKEL*/     static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/ 	char *yy_cp;
/*SKEL*/
/*SKEL*/     yy_cp = (yy_c_buf_p);
/*SKEL*/
/*SKEL*/ 	/* undo effects of setting up yytext */
/*SKEL*/ 	*yy_cp = (yy_hold_char);
/*SKEL*/
/*SKEL*/ 	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
/*SKEL*/ 		{ /* need to shift things up to make room */
/*SKEL*/ 		/* +2 for EOB chars. */
/*SKEL*/ 		yy_size_t number_to_move = (yy_n_chars) + 2;
/*SKEL*/ 		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
/*SKEL*/ 					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
/*SKEL*/ 		char *source =
/*SKEL*/ 				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];
/*SKEL*/
/*SKEL*/ 		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
/*SKEL*/ 			*--dest = *--source;
/*SKEL*/
/*SKEL*/ 		yy_cp += (int) (dest - source);
/*SKEL*/ 		yy_bp += (int) (dest - source);
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
/*SKEL*/ 			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;
/*SKEL*/
/*SKEL*/ 		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
/*SKEL*/ 			YY_FATAL_ERROR( "flex scanner push-back overflow" );
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	*--yy_cp = (char) c;
/*SKEL*/
/* %% [18.0] update yylineno here */

/*SKEL*/
/*SKEL*/ 	(yytext_ptr) = yy_bp;
/*SKEL*/ 	(yy_hold_char) = *yy_cp;
/*SKEL*/ 	(yy_c_buf_p) = yy_cp;
/*SKEL*/ }
/* %if-c-only */
/*SKEL*/
/* %endif */
/*SKEL*/ #endif
/*SKEL*/
/* %if-c-only */
/*SKEL*/ #ifndef YY_NO_INPUT
/*SKEL*/ #ifdef __cplusplus
/*SKEL*/     static int yyinput (void)
/*SKEL*/ #else
/*SKEL*/     static int input  (void)
/*SKEL*/ #endif
/*SKEL*/
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/ 	int c;
/*SKEL*/
/*SKEL*/ 	*(yy_c_buf_p) = (yy_hold_char);
/*SKEL*/
/*SKEL*/ 	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
/*SKEL*/ 		{
/*SKEL*/ 		/* yy_c_buf_p now points to the character we want to return. */
/*SKEL*/ 		 /* If this occurs *before* the EOB characters, then it's a */
/*SKEL*/ 		 /* valid NUL; if not, then we've hit the end of the buffer. */
/*SKEL*/ 		 /**/
/*SKEL*/ 		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
/*SKEL*/ 			/* This was really a NUL. */
/*SKEL*/ 			*(yy_c_buf_p) = '\0';
/*SKEL*/
/*SKEL*/ 		else
/*SKEL*/ 			{ /* need more input */
/*SKEL*/ 			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
/*SKEL*/ 			++(yy_c_buf_p);
/*SKEL*/
/*SKEL*/ 			switch ( yy_get_next_buffer(  ) )
/*SKEL*/ 				{
/*SKEL*/ 				case EOB_ACT_LAST_MATCH:
/*SKEL*/ 					/* This happens because yy_g_n_b() */
/*SKEL*/ 					 /* sees that we've accumulated a */
/*SKEL*/ 					 /* token and flags that we need to */
/*SKEL*/ 					 /* try matching the token before */
/*SKEL*/ 					 /* proceeding.  But for input(), */
/*SKEL*/ 					 /* there's no matching to consider. */
/*SKEL*/ 					 /* So convert the EOB_ACT_LAST_MATCH */
/*SKEL*/ 					 /* to EOB_ACT_END_OF_FILE. */
/*SKEL*/ 					 /**/
/*SKEL*/
/*SKEL*/ 					/* Reset buffer status. */
/*SKEL*/ 					yyrestart(yyin );
/*SKEL*/
/*SKEL*/ 					/*FALLTHROUGH*/
/*SKEL*/
/*SKEL*/ 				case EOB_ACT_END_OF_FILE:
/*SKEL*/ 					{
/*SKEL*/ 					if ( yywrap( ) )
/*SKEL*/ 						return EOF;
/*SKEL*/
/*SKEL*/ 					if ( ! (yy_did_buffer_switch_on_eof) )
/*SKEL*/ 						YY_NEW_FILE;
/*SKEL*/ #ifdef __cplusplus
/*SKEL*/ 					return yyinput();
/*SKEL*/ #else
/*SKEL*/ 					return input();
/*SKEL*/ #endif
/*SKEL*/ 					}
/*SKEL*/
/*SKEL*/ 				case EOB_ACT_CONTINUE_SCAN:
/*SKEL*/ 					(yy_c_buf_p) = (yytext_ptr) + offset;
/*SKEL*/ 					break;
/*SKEL*/ 				}
/*SKEL*/ 			}
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
/*SKEL*/ 	*(yy_c_buf_p) = '\0';	/* preserve yytext */
/*SKEL*/ 	(yy_hold_char) = *++(yy_c_buf_p);
/*SKEL*/
/* %% [19.0] update BOL and yylineno */
/*SKEL*/
/*SKEL*/ 	return c;
/*SKEL*/ }
/* %if-c-only */
/*SKEL*/ #endif	/* ifndef YY_NO_INPUT */
/* %endif */
/*SKEL*/
/*SKEL*/ /** Immediately switch to a different input stream. */
/*SKEL*/  /* @param input_file A readable stream. */
/*SKEL*/  /*  */
/*SKEL*/  /* @note This function does not reset the start condition to @c INITIAL . */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/
/*SKEL*/ 	if ( ! YY_CURRENT_BUFFER ){
/*SKEL*/         yyensure_buffer_stack ();
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE =
/*SKEL*/             yy_create_buffer(yyin,YY_BUF_SIZE );
/*SKEL*/ 	}
/*SKEL*/
/*SKEL*/ 	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
/*SKEL*/ 	yy_load_buffer_state( );
/*SKEL*/ }
/*SKEL*/
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ /** Switch to a different input buffer. */
/*SKEL*/  /* @param new_buffer The new input buffer. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/
/*SKEL*/ 	/* TODO. We should be able to replace this entire function body */
/*SKEL*/ 	 /* with */
/*SKEL*/ 	 /*		yypop_buffer_state(); */
/*SKEL*/ 	 /*		yypush_buffer_state(new_buffer); */
/*SKEL*/      /**/
/*SKEL*/ 	yyensure_buffer_stack ();
/*SKEL*/ 	if ( YY_CURRENT_BUFFER == new_buffer )
/*SKEL*/ 		return;
/*SKEL*/
/*SKEL*/ 	if ( YY_CURRENT_BUFFER )
/*SKEL*/ 		{
/*SKEL*/ 		/* Flush out information for old buffer. */
/*SKEL*/ 		*(yy_c_buf_p) = (yy_hold_char);
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE = new_buffer;
/*SKEL*/ 	yy_load_buffer_state( );
/*SKEL*/
/*SKEL*/ 	/* We don't actually know whether we did this switch during */
/*SKEL*/ 	 /* EOF (yywrap()) processing, but the only time this flag */
/*SKEL*/ 	 /* is looked at is after yywrap() is called, so it's safe */
/*SKEL*/ 	 /* to go ahead and always set it. */
/*SKEL*/ 	 /**/
/*SKEL*/ 	(yy_did_buffer_switch_on_eof) = 1;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/* %if-c-only */
/*SKEL*/ static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/      	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/*SKEL*/ 	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/*SKEL*/ 	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ 	(yy_hold_char) = *(yy_c_buf_p);
/*SKEL*/ }
/*SKEL*/
/*SKEL*/ /** Allocate and initialize an input buffer state. */
/*SKEL*/  /* @param file A readable stream. */
/*SKEL*/  /* @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE. */
/*SKEL*/  /*  */
/*SKEL*/  /* @return the allocated buffer state. */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/ 	YY_BUFFER_STATE b;
/*SKEL*/
/*SKEL*/ 	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
/*SKEL*/ 	if ( ! b )
/*SKEL*/ 		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
/*SKEL*/
/*SKEL*/ 	b->yy_buf_size = (yy_size_t)size;
/*SKEL*/
/*SKEL*/ 	/* yy_ch_buf has to be 2 characters longer than the size given because */
/*SKEL*/ 	 /* we need to put in 2 end-of-buffer characters. */
/*SKEL*/ 	/* */
/*SKEL*/ 	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
/*SKEL*/ 	if ( ! b->yy_ch_buf )
/*SKEL*/ 		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
/*SKEL*/
/*SKEL*/ 	b->yy_is_our_buffer = 1;
/*SKEL*/
/*SKEL*/ 	yy_init_buffer(b,file );
/*SKEL*/
/*SKEL*/ 	return b;
/*SKEL*/ }
/*SKEL*/
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ /** Destroy the buffer. */
/*SKEL*/  /* @param b a buffer created with yy_create_buffer() */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/
/*SKEL*/ 	if ( ! b )
/*SKEL*/ 		return;
/*SKEL*/
/*SKEL*/ 	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;
/*SKEL*/
/*SKEL*/ 	if ( b->yy_is_our_buffer )
/*SKEL*/ 		yyfree((void *) b->yy_ch_buf  );
/*SKEL*/
/*SKEL*/ 	yyfree((void *) b  );
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Initializes or reinitializes a buffer. */
/*SKEL*/  /* This function is sometimes called more than once on the same buffer, */
/*SKEL*/  /* such as during a yyrestart() or at EOF. */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ {
/*SKEL*/ 	int oerrno = errno;
/*SKEL*/
/*SKEL*/ 	yy_flush_buffer(b );
/*SKEL*/
/* %if-c-only */
/*SKEL*/ 	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ 	b->yy_fill_buffer = 1;
/*SKEL*/
/*SKEL*/     /* If b is the current buffer, then yy_init_buffer was _probably_ */
/*SKEL*/      /* called from yyrestart() or through yy_get_next_buffer. */
/*SKEL*/      /* In that case, we don't want to reset the lineno or column. */
/*SKEL*/      /**/
/*SKEL*/     if (b != YY_CURRENT_BUFFER){
/*SKEL*/         b->yy_bs_lineno = 1;
/*SKEL*/         b->yy_bs_column = 0;
/*SKEL*/     }
/*SKEL*/
/* %if-c-only */
/*SKEL*/
/*SKEL*/
/*SKEL*/         b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
/*SKEL*/
/*SKEL*/
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ 	errno = oerrno;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/ /** Discard all buffered characters. On the next scan, YY_INPUT will be called. */
/*SKEL*/  /* @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/     void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/      	if ( ! b )
/*SKEL*/ 		return;
/*SKEL*/
/*SKEL*/ 	b->yy_n_chars = 0;
/*SKEL*/
/*SKEL*/ 	/* We always need two end-of-buffer characters.  The first causes */
/*SKEL*/ 	 /* a transition to the end-of-buffer state.  The second causes */
/*SKEL*/ 	 /* a jam in that state. */
/*SKEL*/ 	 /**/
/*SKEL*/ 	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
/*SKEL*/ 	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
/*SKEL*/
/*SKEL*/ 	b->yy_buf_pos = &b->yy_ch_buf[0];
/*SKEL*/
/*SKEL*/ 	b->yy_at_bol = 1;
/*SKEL*/ 	b->yy_buffer_status = YY_BUFFER_NEW;
/*SKEL*/
/*SKEL*/ 	if ( b == YY_CURRENT_BUFFER )
/*SKEL*/ 		yy_load_buffer_state( );
/*SKEL*/ }
/*SKEL*/
/* %if-c-or-c++ */
/*SKEL*/ /** Pushes the new state onto the stack. The new state becomes */
/*SKEL*/  /*  the current state. This function will allocate the stack */
/*SKEL*/  /*  if necessary. */
/*SKEL*/  /*  @param new_buffer The new state. */
/*SKEL*/  /*   */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/ void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/      	if (new_buffer == NULL)
/*SKEL*/ 		return;
/*SKEL*/
/*SKEL*/ 	yyensure_buffer_stack();
/*SKEL*/
/*SKEL*/ 	/* This block is copied from yy_switch_to_buffer. */
/*SKEL*/ 	if ( YY_CURRENT_BUFFER )
/*SKEL*/ 		{
/*SKEL*/ 		/* Flush out information for old buffer. */
/*SKEL*/ 		*(yy_c_buf_p) = (yy_hold_char);
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
/*SKEL*/ 		}
/*SKEL*/
/*SKEL*/ 	/* Only push if top exists. Otherwise, replace top. */
/*SKEL*/ 	if (YY_CURRENT_BUFFER)
/*SKEL*/ 		(yy_buffer_stack_top)++;
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE = new_buffer;
/*SKEL*/
/*SKEL*/ 	/* copied from yy_switch_to_buffer. */
/*SKEL*/ 	yy_load_buffer_state( );
/*SKEL*/ 	(yy_did_buffer_switch_on_eof) = 1;
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/* %if-c-or-c++ */
/*SKEL*/ /** Removes and deletes the top of the stack, if present. */
/*SKEL*/  /*  The next element becomes the new top. */
/*SKEL*/  /*   */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/ void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/      	if (!YY_CURRENT_BUFFER)
/*SKEL*/ 		return;
/*SKEL*/
/*SKEL*/ 	yy_delete_buffer(YY_CURRENT_BUFFER );
/*SKEL*/ 	YY_CURRENT_BUFFER_LVALUE = NULL;
/*SKEL*/ 	if ((yy_buffer_stack_top) > 0)
/*SKEL*/ 		--(yy_buffer_stack_top);
/*SKEL*/
/*SKEL*/ 	if (YY_CURRENT_BUFFER) {
/*SKEL*/ 		yy_load_buffer_state( );
/*SKEL*/ 		(yy_did_buffer_switch_on_eof) = 1;
/*SKEL*/ 	}
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/* %if-c-or-c++ */
/*SKEL*/ /* Allocates the stack if it does not exist. */
/*SKEL*/  /*  Guarantees space for at least one push. */
/*SKEL*/  /**/
/* %if-c-only */
/*SKEL*/ static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/ {
/*SKEL*/ 	yy_size_t num_to_alloc;
/*SKEL*/
/*SKEL*/ 	if (!(yy_buffer_stack)) {
/*SKEL*/
/*SKEL*/ 		/* First allocation is just for 2 elements, since we don't know if this */
/*SKEL*/ 		 /* scanner will even need a stack. We use 2 instead of 1 to avoid an */
/*SKEL*/ 		 /* immediate realloc on the next call. */
/*SKEL*/         /* */
/*SKEL*/ 		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
/*SKEL*/ 		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
/*SKEL*/ 								(num_to_alloc * sizeof(struct yy_buffer_state*)
/*SKEL*/ 								);
/*SKEL*/ 		if ( ! (yy_buffer_stack) )
/*SKEL*/ 			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
/*SKEL*/
/*SKEL*/
/*SKEL*/ 		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
/*SKEL*/
/*SKEL*/ 		(yy_buffer_stack_max) = num_to_alloc;
/*SKEL*/ 		(yy_buffer_stack_top) = 0;
/*SKEL*/ 		return;
/*SKEL*/ 	}
/*SKEL*/
/*SKEL*/ 	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){
/*SKEL*/
/*SKEL*/ 		/* Increase the buffer to prepare for a possible push. */
/*SKEL*/ 		yy_size_t grow_size = 8 /* arbitrary grow size */;
/*SKEL*/
/*SKEL*/ 		num_to_alloc = (yy_buffer_stack_max) + grow_size;
/*SKEL*/ 		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
/*SKEL*/ 								((yy_buffer_stack),
/*SKEL*/ 								num_to_alloc * sizeof(struct yy_buffer_state*)
/*SKEL*/ 								);
/*SKEL*/ 		if ( ! (yy_buffer_stack) )
/*SKEL*/ 			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
/*SKEL*/
/*SKEL*/ 		/* zero only the new slots.*/
/*SKEL*/ 		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
/*SKEL*/ 		(yy_buffer_stack_max) = num_to_alloc;
/*SKEL*/ 	}
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-c-only */
/*SKEL*/ /** Setup the input buffer state to scan directly from a user-specified character buffer. */
/*SKEL*/  /* @param base the character buffer */
/*SKEL*/  /* @param size the size in bytes of the character buffer */
/*SKEL*/  /*  */
/*SKEL*/  /* @return the newly allocated buffer state object.  */
/*SKEL*/  /**/
/*SKEL*/ YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
/*SKEL*/ {
/*SKEL*/ 	YY_BUFFER_STATE b;
/*SKEL*/
/*SKEL*/ 	if ( size < 2 ||
/*SKEL*/ 	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
/*SKEL*/ 	     base[size-1] != YY_END_OF_BUFFER_CHAR )
/*SKEL*/ 		/* They forgot to leave room for the EOB's. */
/*SKEL*/ 		return 0;
/*SKEL*/
/*SKEL*/ 	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
/*SKEL*/ 	if ( ! b )
/*SKEL*/ 		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
/*SKEL*/
/*SKEL*/ 	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
/*SKEL*/ 	b->yy_buf_pos = b->yy_ch_buf = base;
/*SKEL*/ 	b->yy_is_our_buffer = 0;
/*SKEL*/ 	b->yy_input_file = 0;
/*SKEL*/ 	b->yy_n_chars = b->yy_buf_size;
/*SKEL*/ 	b->yy_is_interactive = 0;
/*SKEL*/ 	b->yy_at_bol = 1;
/*SKEL*/ 	b->yy_fill_buffer = 0;
/*SKEL*/ 	b->yy_buffer_status = YY_BUFFER_NEW;
/*SKEL*/
/*SKEL*/ 	yy_switch_to_buffer(b  );
/*SKEL*/
/*SKEL*/ 	return b;
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-c-only */
/*SKEL*/ /** Setup the input buffer state to scan a string. The next call to yylex() will */
/*SKEL*/  /* scan from a @e copy of @a str. */
/*SKEL*/  /* @param yystr a NUL-terminated string to scan */
/*SKEL*/  /*  */
/*SKEL*/  /* @return the newly allocated buffer state object. */
/*SKEL*/  /* @note If you want to scan bytes that may contain NUL values, then use */
/*SKEL*/  /*       yy_scan_bytes() instead. */
/*SKEL*/  /**/
/*SKEL*/ YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
/*SKEL*/ {
/*SKEL*/
/*SKEL*/ 	return yy_scan_bytes(yystr,strlen(yystr) );
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/* %if-c-only */
/*SKEL*/ /** Setup the input buffer state to scan the given bytes. The next call to yylex() will */
/*SKEL*/  /* scan from a @e copy of @a bytes. */
/*SKEL*/  /* @param yybytes the byte buffer to scan */
/*SKEL*/  /* @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes. */
/*SKEL*/  /*  */
/*SKEL*/  /* @return the newly allocated buffer state object. */
/*SKEL*/  /**/
/*SKEL*/ YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
/*SKEL*/ {
/*SKEL*/ 	YY_BUFFER_STATE b;
/*SKEL*/ 	char *buf;
/*SKEL*/ 	yy_size_t n;
/*SKEL*/ 	yy_size_t i;
/*SKEL*/
/*SKEL*/ 	/* Get memory for full buffer, including space for trailing EOB's. */
/*SKEL*/ 	n = _yybytes_len + 2;
/*SKEL*/ 	buf = (char *) yyalloc(n  );
/*SKEL*/ 	if ( ! buf )
/*SKEL*/ 		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
/*SKEL*/
/*SKEL*/ 	for ( i = 0; i < _yybytes_len; ++i )
/*SKEL*/ 		buf[i] = yybytes[i];
/*SKEL*/
/*SKEL*/ 	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;
/*SKEL*/
/*SKEL*/ 	b = yy_scan_buffer(buf,n );
/*SKEL*/ 	if ( ! b )
/*SKEL*/ 		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
/*SKEL*/
/*SKEL*/ 	/* It's okay to grow etc. this buffer, and we should throw it */
/*SKEL*/ 	 /* away when we're done. */
/*SKEL*/ 	 /**/
/*SKEL*/ 	b->yy_is_our_buffer = 1;
/*SKEL*/
/*SKEL*/ 	return b;
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/ #ifndef YY_EXIT_FAILURE
/*SKEL*/ #define YY_EXIT_FAILURE 2
/*SKEL*/ #endif
/*SKEL*/
/* %if-c-only */
/*SKEL*/ static void yy_fatal_error (yyconst char* msg )
/*SKEL*/ {
/*SKEL*/ 	 	 	(void) fprintf( stderr, "%s\n", msg );
/*SKEL*/ 	exit( YY_EXIT_FAILURE );
/*SKEL*/ }
/* %endif */
/* %if-c++-only */
/* %endif */
/*SKEL*/
/*SKEL*/ /* Redefine yyless() so it works in section 3 code. */
/*SKEL*/
/*SKEL*/ #undef yyless
/*SKEL*/ #define yyless(n) \
/*SKEL*/ 	do \
/*SKEL*/ 		{ \
/*SKEL*/ 		/* Undo effects of setting up yytext. */ \
/*SKEL*/         int yyless_macro_arg = (n); \
/*SKEL*/         YY_LESS_LINENO(yyless_macro_arg);\
/*SKEL*/ 		yytext[yyleng] = (yy_hold_char); \
/*SKEL*/ 		(yy_c_buf_p) = yytext + yyless_macro_arg; \
/*SKEL*/ 		(yy_hold_char) = *(yy_c_buf_p); \
/*SKEL*/ 		*(yy_c_buf_p) = '\0'; \
/*SKEL*/ 		yyleng = yyless_macro_arg; \
/*SKEL*/ 		} \
/*SKEL*/ 	while ( 0 )
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* Accessor  methods (get/set functions) to struct members. */
/*SKEL*/
/* %if-c-only */
/* %if-reentrant */
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Get the current line number. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/*SKEL*/ int yyget_lineno  (void)
/*SKEL*/ {
/*SKEL*/
/*SKEL*/
/*SKEL*/     return yylineno;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Get the input stream. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/*SKEL*/ FILE *yyget_in  (void)
/*SKEL*/ {
/*SKEL*/          return yyin;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Get the output stream. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/*SKEL*/ FILE *yyget_out  (void)
/*SKEL*/ {
/*SKEL*/          return yyout;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Get the length of the current token. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/*SKEL*/ yy_size_t yyget_leng  (void)
/*SKEL*/ {
/*SKEL*/          return yyleng;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Get the current token. */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/*SKEL*/
/*SKEL*/ char *yyget_text  (void)
/*SKEL*/ {
/*SKEL*/          return yytext;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/* %if-reentrant */
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Set the current line number. */
/*SKEL*/  /* @param _line_number line number */
/*SKEL*/  /*  */
/*SKEL*/  /**/
/*SKEL*/ void yyset_lineno (int  _line_number )
/*SKEL*/ {
/*SKEL*/
/*SKEL*/
/*SKEL*/     yylineno = _line_number;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/

/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /** Set the input stream. This does not discard the current */
/*SKEL*/  /* input buffer. */
/*SKEL*/  /* @param _in_str A readable stream. */
/*SKEL*/  /*  */
/*SKEL*/  /* @see yy_switch_to_buffer */
/*SKEL*/  /**/
/*SKEL*/ void yyset_in (FILE *  _in_str )
/*SKEL*/ {
/*SKEL*/          yyin = _in_str ;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_out (FILE *  _out_str )
/*SKEL*/ {
/*SKEL*/          yyout = _out_str ;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ int yyget_debug  (void)
/*SKEL*/ {
/*SKEL*/          return yy_flex_debug;
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyset_debug (int  _bdebug )
/*SKEL*/ {
/*SKEL*/          yy_flex_debug = _bdebug ;
/*SKEL*/ }
/*SKEL*/
/* %endif */
/*SKEL*/
/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */
/*SKEL*/
/* %if-c-only */
/*SKEL*/ static int yy_init_globals (void)
/*SKEL*/ {
/*SKEL*/          /* Initialization is the same as for the non-reentrant scanner. */
/*SKEL*/     /* This function is called from yylex_destroy(), so don't allocate here. */
/*SKEL*/     /* */
/*SKEL*/

/*SKEL*/     (yy_buffer_stack) = 0;
/*SKEL*/     (yy_buffer_stack_top) = 0;
/*SKEL*/     (yy_buffer_stack_max) = 0;
/*SKEL*/     (yy_c_buf_p) = (char *) 0;
/*SKEL*/     (yy_init) = 0;
/*SKEL*/     (yy_start) = 0;
/*SKEL*/

/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/ /* Defined in main.c */
/*SKEL*/ #ifdef YY_STDINIT
/*SKEL*/     yyin = stdin;
/*SKEL*/     yyout = stdout;
/*SKEL*/ #else
/*SKEL*/     yyin = (FILE *) 0;
/*SKEL*/     yyout = (FILE *) 0;
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/     /* For future reference: Set errno on error, since we are called by */
/*SKEL*/     /* yylex_init() */
/*SKEL*/     /* */
/*SKEL*/     return 0;
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/*SKEL*/ /* yylex_destroy is for both reentrant and non-reentrant scanners. */
/*SKEL*/ int yylex_destroy  (void)
/*SKEL*/ {
/*SKEL*/
/*SKEL*/     /* Pop the buffer stack, destroying each element. */
/*SKEL*/ 	while(YY_CURRENT_BUFFER){
/*SKEL*/ 		yy_delete_buffer(YY_CURRENT_BUFFER  );
/*SKEL*/ 		YY_CURRENT_BUFFER_LVALUE = NULL;
/*SKEL*/ 		yypop_buffer_state();
/*SKEL*/ 	}
/*SKEL*/
/*SKEL*/ 	/* Destroy the stack itself. */
/*SKEL*/ 	yyfree((yy_buffer_stack) );
/*SKEL*/ 	(yy_buffer_stack) = NULL;
/*SKEL*/

/*SKEL*/

/*SKEL*/
/*SKEL*/     /* Reset the globals. This is important in a non-reentrant scanner so the next time */
/*SKEL*/     /* yylex() is called, initialization will occur. */
/*SKEL*/     yy_init_globals( );
/*SKEL*/
/* %if-reentrant */
/* %endif */
/*SKEL*/     return 0;
/*SKEL*/ }
/* %endif */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ /* */
/*SKEL*/  /* Internal utility routines. */
/*SKEL*/  /* */
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifndef yytext_ptr
/*SKEL*/ static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
/*SKEL*/ {
/*SKEL*/ 	 	
/*SKEL*/ 	int i;
/*SKEL*/ 	for ( i = 0; i < n; ++i )
/*SKEL*/ 		s1[i] = s2[i];
/*SKEL*/ }
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ #ifdef YY_NEED_STRLEN
/*SKEL*/ static int yy_flex_strlen (yyconst char * s )
/*SKEL*/ {
/*SKEL*/ 	int n;
/*SKEL*/ 	for ( n = 0; s[n]; ++n )
/*SKEL*/ 		;
/*SKEL*/
/*SKEL*/ 	return n;
/*SKEL*/ }
/*SKEL*/ #endif
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void *yyalloc (yy_size_t  size )
/*SKEL*/ {
/*SKEL*/ 	 	 	return (void *) malloc( size );
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void *yyrealloc  (void * ptr, yy_size_t  size )
/*SKEL*/ {
/*SKEL*/ 	 	
/*SKEL*/ 	/* The cast to (char *) in the following accommodates both */
/*SKEL*/ 	 /* implementations that use char* generic pointers, and those */
/*SKEL*/ 	 /* that use void* generic pointers.  It works with the latter */
/*SKEL*/ 	 /* because both ANSI C and C++ allow castless assignment from */
/*SKEL*/ 	 /* any pointer type to void*, and deal with argument conversions */
/*SKEL*/ 	 /* as though doing an assignment. */
/*SKEL*/ 	 /* */
/*SKEL*/ 	return (void *) realloc( (char *) ptr, size );
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/*SKEL*/
/*SKEL*/ void yyfree (void * ptr )
/*SKEL*/ {
/*SKEL*/ 	 	 	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
/*SKEL*/ }
/*SKEL*/
/*SKEL*/
/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */
/*SKEL*/
/*SKEL*/

/*SKEL*/
/* %ok-for-header */

/*SKEL*/
#line 17 "demo.l"



int main() {
    yylex();
    return 0;
}

